version: '3.8'
services:
  vite:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8082:82"
    networks:
      - cellscope_network

networks:
  cellscope_network:
    external: true
